apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zero2prod
spec:
  template:
   spec:
    containers:
    #  - image: https://hub.docker.com/repository/docker/tolumide/zero2prod
    #  - image: europe-west3-docker.pkg.dev/tolumide-gcp/tolumide-zero2prod
     - image: gcr.io/tolumide-gcp/tolumide-zero2prod
       resources:
        limits:
         memory: 512M
         cpu: '1'
   metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '1'